In [2]:
import torch
print(torch.__version__) 
print(torch.cuda.is_available()) 


2.5.1
True


In [3]:
vector = torch.tensor([0,1])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([0, 1])
Dimension of my vector is 1


In [4]:
vector = torch.tensor([[0,1],[1,2]])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([[0, 1],
        [1, 2]])
Dimension of my vector is 2


In [5]:
tensor = torch.tensor([[[0,1],[1,2],[2,3]]])
print(tensor)
print(f"Dimension of my vector is {tensor.ndim}")

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
Dimension of my vector is 3


In [8]:
print(tensor.shape)
#Means 1 dimension of shape 3,2

torch.Size([1, 3, 2])


In [13]:
print(tensor[0])
print(tensor[0][0])
print(tensor[0][2])
print(tensor[0][2][1])

tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([0, 1])
tensor([2, 3])
tensor(3)
