In [2]:
import torch
print(torch.__version__) 
print(torch.cuda.is_available()) 


2.5.1
True


In [3]:
vector = torch.tensor([0,1])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([0, 1])
Dimension of my vector is 1


In [4]:
vector = torch.tensor([[0,1],[1,2]])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([[0, 1],
        [1, 2]])
Dimension of my vector is 2


In [5]:
tensor = torch.tensor([[[0,1],[1,2],[2,3]]])
print(tensor)
print(f"Dimension of my vector is {tensor.ndim}")

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
Dimension of my vector is 3


In [8]:
print(tensor.shape)
#Means 1 dimension of shape 3,2

torch.Size([1, 3, 2])


In [13]:
print(tensor[0])
print(tensor[0][0])
print(tensor[0][2])
print(tensor[0][2][1])

tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([0, 1])
tensor([2, 3])
tensor(3)


In [15]:
print(tensor[:,2,1])
print(tensor[:,2,1][0])

tensor([3])
tensor(3)


In [21]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.3054, 0.7823, 0.3160, 0.0240],
        [0.6513, 0.5425, 0.9215, 0.4992],
        [0.4856, 0.4680, 0.3390, 0.3090]])
2
torch.Size([3, 4])
<bound method Tensor.share_memory_ of tensor([[0.3054, 0.7823, 0.3160, 0.0240],
        [0.6513, 0.5425, 0.9215, 0.4992],
        [0.4856, 0.4680, 0.3390, 0.3090]])>


In [27]:
input = 30 
hidden = 100
weights_tensor = torch.rand(size=(2,input, hidden))
print(weights_tensor)
print(weights_tensor.ndim)
print(weights_tensor.shape)
print(weights_tensor.im_show)

tensor([[[1.8787e-01, 1.6066e-01, 4.1178e-01,  ..., 2.1017e-02,
          4.1278e-01, 9.6698e-01],
         [9.1676e-01, 2.3484e-04, 5.6834e-01,  ..., 7.8102e-01,
          6.1861e-01, 7.4621e-01],
         [1.0075e-01, 3.0306e-01, 5.3943e-02,  ..., 2.1460e-01,
          8.7529e-01, 7.7888e-01],
         ...,
         [2.9463e-01, 4.3851e-01, 4.9743e-01,  ..., 8.1679e-01,
          7.6424e-01, 5.1870e-01],
         [5.0675e-01, 5.3916e-02, 8.0144e-01,  ..., 9.2994e-01,
          9.5421e-01, 9.7131e-01],
         [6.2736e-01, 7.0483e-01, 2.2597e-01,  ..., 3.0435e-01,
          6.9888e-02, 1.6342e-01]],

        [[2.9667e-01, 6.9466e-01, 5.6713e-01,  ..., 2.9190e-01,
          5.1642e-01, 3.2142e-01],
         [2.7551e-01, 3.1721e-01, 6.6847e-01,  ..., 2.1098e-01,
          4.3824e-01, 2.4051e-01],
         [7.3880e-01, 4.0995e-01, 6.7096e-01,  ..., 3.1021e-01,
          6.8197e-01, 6.9913e-01],
         ...,
         [4.1831e-03, 5.4055e-01, 8.6419e-01,  ..., 5.2695e-01,
          4.957

In [28]:
random_tensor_image = torch.rand(size=(150, 150, 3))
print(random_tensor_image.ndim)
print(random_tensor_image.shape)
# print(random_tensor_image)

3
torch.Size([150, 150, 3])
tensor([[[0.0272, 0.5496, 0.1382],
         [0.1252, 0.2332, 0.7125],
         [0.4899, 0.1653, 0.2373],
         ...,
         [0.8925, 0.2908, 0.1958],
         [0.6699, 0.0953, 0.9573],
         [0.9228, 0.7210, 0.4256]],

        [[0.4522, 0.0742, 0.6150],
         [0.3264, 0.7174, 0.4198],
         [0.6000, 0.0456, 0.0866],
         ...,
         [0.6130, 0.4342, 0.8270],
         [0.1848, 0.8524, 0.7618],
         [0.3520, 0.7059, 0.4784]],

        [[0.8292, 0.0150, 0.2378],
         [0.9266, 0.2865, 0.1052],
         [0.6616, 0.1309, 0.4007],
         ...,
         [0.2278, 0.5497, 0.1832],
         [0.5750, 0.5168, 0.5972],
         [0.4966, 0.0792, 0.4803]],

        ...,

        [[0.7765, 0.7268, 0.8053],
         [0.2566, 0.5755, 0.8171],
         [0.6441, 0.6588, 0.2980],
         ...,
         [0.0740, 0.9205, 0.2286],
         [0.6937, 0.1880, 0.3755],
         [0.2136, 0.0118, 0.9057]],

        [[0.4740, 0.8347, 0.2033],
         [0.6406, 0

In [5]:
import torch

In [6]:
zeros = torch.zeros(size=(3,4))
print(zeros.ndim)
print(zeros.shape)
print(zeros)

2
torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
