In [2]:
import torch
print(torch.__version__) 
print(torch.cuda.is_available()) 


2.5.1
True


In [3]:
vector = torch.tensor([0,1])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([0, 1])
Dimension of my vector is 1


In [4]:
vector = torch.tensor([[0,1],[1,2]])
print(vector)
print(f"Dimension of my vector is {vector.ndim}")

tensor([[0, 1],
        [1, 2]])
Dimension of my vector is 2


In [5]:
tensor = torch.tensor([[[0,1],[1,2],[2,3]]])
print(tensor)
print(f"Dimension of my vector is {tensor.ndim}")

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
Dimension of my vector is 3


In [8]:
print(tensor.shape)
#Means 1 dimension of shape 3,2

torch.Size([1, 3, 2])


In [13]:
print(tensor[0])
print(tensor[0][0])
print(tensor[0][2])
print(tensor[0][2][1])

tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([0, 1])
tensor([2, 3])
tensor(3)


In [15]:
print(tensor[:,2,1])
print(tensor[:,2,1][0])

tensor([3])
tensor(3)


In [21]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.3054, 0.7823, 0.3160, 0.0240],
        [0.6513, 0.5425, 0.9215, 0.4992],
        [0.4856, 0.4680, 0.3390, 0.3090]])
2
torch.Size([3, 4])
<bound method Tensor.share_memory_ of tensor([[0.3054, 0.7823, 0.3160, 0.0240],
        [0.6513, 0.5425, 0.9215, 0.4992],
        [0.4856, 0.4680, 0.3390, 0.3090]])>


In [27]:
input = 30 
hidden = 100
weights_tensor = torch.rand(size=(2,input, hidden))
print(weights_tensor)
print(weights_tensor.ndim)
print(weights_tensor.shape)
print(weights_tensor.im_show)

tensor([[[1.8787e-01, 1.6066e-01, 4.1178e-01,  ..., 2.1017e-02,
          4.1278e-01, 9.6698e-01],
         [9.1676e-01, 2.3484e-04, 5.6834e-01,  ..., 7.8102e-01,
          6.1861e-01, 7.4621e-01],
         [1.0075e-01, 3.0306e-01, 5.3943e-02,  ..., 2.1460e-01,
          8.7529e-01, 7.7888e-01],
         ...,
         [2.9463e-01, 4.3851e-01, 4.9743e-01,  ..., 8.1679e-01,
          7.6424e-01, 5.1870e-01],
         [5.0675e-01, 5.3916e-02, 8.0144e-01,  ..., 9.2994e-01,
          9.5421e-01, 9.7131e-01],
         [6.2736e-01, 7.0483e-01, 2.2597e-01,  ..., 3.0435e-01,
          6.9888e-02, 1.6342e-01]],

        [[2.9667e-01, 6.9466e-01, 5.6713e-01,  ..., 2.9190e-01,
          5.1642e-01, 3.2142e-01],
         [2.7551e-01, 3.1721e-01, 6.6847e-01,  ..., 2.1098e-01,
          4.3824e-01, 2.4051e-01],
         [7.3880e-01, 4.0995e-01, 6.7096e-01,  ..., 3.1021e-01,
          6.8197e-01, 6.9913e-01],
         ...,
         [4.1831e-03, 5.4055e-01, 8.6419e-01,  ..., 5.2695e-01,
          4.957